server:
  port: 9012  #网关端口
spring:
  application:
    name: dream-managerweb
  rabbitmq:
    host: 192.168.81.136
jwt:
  config:
    key: ustc
eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:

    dream-base: #基础
      path: /base/** #配置请求URL的请求规则
      serviceId: dream-base #指定Eureka注册中心中的服务id
    dream-user: #用户
      path: /user/** #配置请求URL的请求规则
      serviceId: dream-user #指定Eureka注册中心中的服务id
    dream-search: #搜索
      path: /search/** #配置请求URL的请求规则
      serviceId: dream-search #指定Eureka注册中心中的服务id
    dream-commodity: #用户商品
      path: /goods/** #配置请求URL的请求规则
      serviceId: dream-goods #指定Eureka注册中心中的服务id
    dream-shop: #用户商城
      path: /shop/** #配置请求URL的请求规则
      serviceId: dream-shop #指定Eureka注册中心中的服务id
    linxi-school: #学校
      path: /education/** #配置请求URL的请求规则
      serviceId: linxi-school #指定Eureka注册中心中的服务id
    liuxue-warehouse: #仓库
      path: /warehouse/** #配置请求URL的请求规则
      serviceId: liuxue-warehouse #指定Eureka注册中心中的服务id