server:
  port: 9011  #网关端口
spring:
  application:
    name: dream-manager
  rabbitmq:
    host: 192.168.81.136
jwt:
  config:
    key: ustc
eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    dream-base: #基础
      path: /base/** #配置请求URL的请求规则
      serviceId: dream-base #指定Eureka注册中心中的服务id
    dream-user: #用户
      path: /user/** #配置请求URL的请求规则
      serviceId: dream-user #指定Eureka注册中心中的服务id
    dream-commodity: #用户商品
      path: /goods/** #配置请求URL的请求规则
      serviceId: dream-goods #指定Eureka注册中心中的服务id