server:
  port: 9013
spring:
  application:
    name: dream_shop
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.81.136:3306/dream_shop?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  redis:
    host: 192.168.81.136
    port: 6379
  rabbitmq:
    host: 192.168.81.136
jwt:
  config:
    key: ustc
    ttl: 360000000000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
