server:
  port: 9009
spring:
  application:
    name: dream-sms
  rabbitmq:
    host: 192.168.81.136
    
eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
aliyun:
  sms:
    accessKeyId: LTAIawZE0vDDFT4n
    accessKeySecret: guYVF2XR5Nmvzw8GgSHhD4hRUjRMiI
    template_code: SMS_166096302
    sign_name: 梦夕网中科大工程实践
