server:
  port: 9009
spring:
  application:
    name: dream-sms
  rabbitmq:
    host: 192.168.81.136
aliyun:
  sms:
    accessKeyId: LTAIawZE0vDDFT4n
    accessKeySecret: guYVF2XR5Nmvzw8GgSHhD4hRUjRMiI
    template_code: SMS_166096302
    sign_name: 梦夕网中科大工程实践
